version: '3.8'

services:
  research-agent-urban:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research-agent-urban
    restart: unless-stopped
    
    # Volumes para persistência
    volumes:
      - agent_data:/app/data
      - agent_browser:/app/browser-data
      - agent_cache:/app/cache
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
    environment:
      # Configurações básicas
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      
      # URLs e configurações do sistema
      - RIDES_LOGIN_URL=${RIDES_LOGIN_URL:-https://carreira.ridesapp.com.br/driver/login}
      - RIDES_USERNAME=${RIDES_USERNAME}
      - RIDES_PASSWORD=${RIDES_PASSWORD}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      
      # Configurações do navegador
      - DISPLAY=:99
      - BROWSER_HEADLESS=${BROWSER_HEADLESS:-true}
      - BROWSER_TIMEOUT=${BROWSER_TIMEOUT:-30000}
      
      # Configurações de scraping
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-15}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      
      # Configurações de rede
      - PORT=${PORT:-3000}
      
    ports:
      - "${PORT:-3000}:3000"
      
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Recursos
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
          
    # Políticas de segurança
    security_opt:
      - no-new-privileges:true
      
    # Configurações de rede
    networks:
      - research_agent_network

# Volumes nomeados para persistência
volumes:
  agent_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/research-agent-urban/data
      
  agent_browser:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/research-agent-urban/browser-data
      
  agent_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/research-agent-urban/cache

# Rede isolada
networks:
  research_agent_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
